### ISSUE TITLE
Undefined permissions stopping install

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_blogs#24]
On trying to install localgov_blogs on a clean install I get this error.

> Adding non-existent permissions to a role is not allowed. The incorrect permissions are "add scheduled transitions node localgov_blog_post", "reschedule scheduled transitions node localgov_blog_post", "view scheduled transitions node localgov_blog_pos  
>   t", "add scheduled transitions node localgov_blog_channel", "reschedule scheduled transitions node localgov_blog_channel", "view scheduled transitions node localgov_blog_channel". 

Guessing Scheduled transitions needs to be enabled as a dependency?

**Comment by danchamp** [comment]
I've just seen this on an install on an existing site with workflow / scheduled transitions enabled. In this case it was because Blog channel and Blog post were not enabled entity types for scheduled transitions.

There is a check for localgov_workflows being enabled, not sure though if this is required / desired: https://github.com/localgovdrupal/localgov_blogs/blob/93a3a9eff37f0e2a6522c71c56697f931f153918/localgov_blogs.module#L214-L240

I couldn't find any other localgov modules that try to enable scheduled transitions.

**Comment by stephen-cox** [comment]
I believe there are other modules that configure scheduled transitions on install, but will have to check.

This is necessary to use the review date stuff, so assuming that being able to set review dates for blog content is desirable, we'll need an install hook to check scheduled transitions is enabled and, if so, add blog content.

**Comment by ekes** [comment]
You get the error _if_ scheduled transitions has been enabled.

This installs:
`drush si localgov; drush en localgov_blogs; drush en localgov_workflows; `

This fails:
`drush si localgov; drush en localgov_workflows; drush en localgov_blogs;`

Where and when should these transitions be being enabled/created?

**Comment by ekes** [comment]
OK I made a start on it I'll put a note on the PR
