### ISSUE TITLE
Promoted blog post display

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_blogs#8]
Most of the .gov.uk blogs only have one promoted blog post, and it appears full width.  (example: https://gds.blog.gov.uk/ ) 

@willguv thinks that they _can_ add up to three, but the following two display smaller after the first. 

Currently out blogs allow for three promoted blogs.

Options:

1. Keep it as is, three in a row
2. Change display to show the first as per .gov patterns and do something with the other two
3. Reduce the number of promoted options to 1

@markconroy thoughts?

**Comment by finnlewis** [comment]
In planning, we're thinking option 2 from above.

**Comment by markconroy** [comment]
I don't have any particular preference here to be honest. Each approach has merits.

If we are keeping the 3-in-a-row approach, I'd <strong>strongly</strong> (see what I did there?) encourage us to create a card view mode and template instead of trying to mash css from a teaser template into a card type layout. https://github.com/localgovdrupal/localgov_core/issues/57
